### ISSUE TITLE
Is this an app?

### ISSUE THREAD

**Issue by psivesely** [unixninja92/Div-III-Client#1]
Just curious--pls inform.

**Comment by fowlslegs** [comment]
Watch my repo and I'll watch yours back?

**Comment by fowlslegs** [comment]
"DPs on the DL."

**Comment by unixninja92** [comment]
It's the client side code for my div. GUI is separate at the moment.

**Comment by psivesely** [comment]
So it's an app?

**Comment by psivesely** [comment]
Pls verify.

**Comment by unixninja92** [comment]
Yeah. Not fully functional yet though.

**Comment by psivesely** [comment]
Great. I love apps. Pls let me know when I can download it in the App Store. Tyvm!!!
